// <auto-generated />
namespace XOcsatt.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Creatingbackupmachine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creatingbackupmachine));
        
        string IMigrationMetadata.Id
        {
            get { return "201601281719429_Creating backup machine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
